-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 11:55:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema martsnp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema martsnp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `martsnp` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema martsnp_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema martsnp_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `martsnp_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `martsnp` ;

-- -----------------------------------------------------
-- Table `martsnp`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `account_type` VARCHAR(50) NOT NULL DEFAULT 'buyer',
  `phone` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`sellers` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `subscription` DATETIME NOT NULL,
  `end_limit` INT(11) NOT NULL DEFAULT '7',
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sellers_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_sellers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`store_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`store_types` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  `store_type` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`stores` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `store_image` VARCHAR(255) NOT NULL,
  `total_products` INT(11) NOT NULL DEFAULT '0',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `sellers_id` BIGINT(20) UNSIGNED NOT NULL,
  `store_types_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `sellers_id`),
  INDEX `fk_stores_sellers1_idx` (`sellers_id` ASC) VISIBLE,
  INDEX `fk_stores_store_types1_idx` (`store_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_stores_sellers1`
    FOREIGN KEY (`sellers_id`)
    REFERENCES `martsnp`.`sellers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stores_store_types1`
    FOREIGN KEY (`store_types_id`)
    REFERENCES `martsnp`.`store_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`products` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `category_name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` VARCHAR(255) NOT NULL,
  `product_size` VARCHAR(255) NOT NULL,
  `rating` INT(11) NOT NULL DEFAULT '0',
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `store_id` BIGINT(20) UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_stores1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `martsnp`.`stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `martsnp`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`Payment_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`Payment_Details` (
  `Payment_id` INT NOT NULL,
  `payment_type` VARCHAR(45) NOT NULL,
  `Payment_status` VARCHAR(45) NOT NULL,
  `Allowed` BINARY(1) NULL,
  PRIMARY KEY (`Payment_id`),
  UNIQUE INDEX `Payment_id_UNIQUE` (`Payment_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`orders` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `price` VARCHAR(255) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `store_id` VARCHAR(255) NOT NULL,
  `confirmed` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL,
  `product_id` BIGINT(20) UNSIGNED NULL,
  `Payment_Details_Payment_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_products2_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_orders_Payment_Details1_idx` (`Payment_Details_Payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `martsnp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products2`
    FOREIGN KEY (`product_id`)
    REFERENCES `martsnp`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_Payment_Details1`
    FOREIGN KEY (`Payment_Details_Payment_id`)
    REFERENCES `martsnp`.`Payment_Details` (`Payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`cart` (
  `id` INT NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  `products_id` BIGINT(20) UNSIGNED NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_cart_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`images` (
  `products_id` BIGINT(20) UNSIGNED NOT NULL,
  INDEX `fk_images_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`variant` (
  `id` INT NOT NULL,
  `description` MEDIUMTEXT NULL,
  `name` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`product_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`product_variant` (
  `products_id` BIGINT(20) UNSIGNED NOT NULL,
  `variant_id` INT NOT NULL,
  INDEX `fk_product_variant_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_product_variant_variant1_idx` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_variant_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_variant_variant1`
    FOREIGN KEY (`variant_id`)
    REFERENCES `martsnp`.`variant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `martsnp`.`Admins(/site_owners)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp`.`Admins(/site_owners)` (
  `id` INT NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `FName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `users_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_Admins(/site_owners)_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Admins(/site_owners)_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `martsnp_project` ;

-- -----------------------------------------------------
-- Table `martsnp_project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`users` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `users_email_unique` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`admins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Admins(/site_owners)_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Admins(/site_owners)_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`store_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`store_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NOT NULL,
  `store_type` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `users_id` (`users_id` ASC) VISIBLE,
  CONSTRAINT `users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`stores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `store_image` VARCHAR(255) NOT NULL,
  `store_types_id` BIGINT UNSIGNED NOT NULL,
  `users_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stores_store_types1_idx` (`store_types_id` ASC) VISIBLE,
  INDEX `store_users_id` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_stores_store_types1`
    FOREIGN KEY (`store_types_id`)
    REFERENCES `martsnp_project`.`store_types` (`id`),
  CONSTRAINT `store_users_id`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`products` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` INT NOT NULL,
  `store_id` BIGINT UNSIGNED NOT NULL,
  `category_id` INT NOT NULL,
  `rating` INT NOT NULL DEFAULT '0',
  `product_size` VARCHAR(100) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_stores1_idx` (`store_id` ASC) VISIBLE,
  INDEX `fk_products_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `martsnp_project`.`stores` (`id`),
  CONSTRAINT `product_category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `martsnp_project`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT UNSIGNED NOT NULL,
  `products_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cart_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_cart_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp_project`.`products` (`id`),
  CONSTRAINT `fk_cart_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`images` (
  `products_id` BIGINT UNSIGNED NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  INDEX `fk_images_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_images_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp_project`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`payment_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`payment_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NOT NULL,
  `payment_status` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Payment_id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`orders` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `user_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `product_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `payment_details_payment_id` INT NOT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_orders_products2_idx` (`product_id` ASC) VISIBLE,
  INDEX `orders_payment_details_payment_id` (`payment_details_payment_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_products2`
    FOREIGN KEY (`product_id`)
    REFERENCES `martsnp_project`.`products` (`id`),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `martsnp_project`.`users` (`id`),
  CONSTRAINT `orders_payment_details_payment_id`
    FOREIGN KEY (`payment_details_payment_id`)
    REFERENCES `martsnp_project`.`payment_details` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`variant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`product_variant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`product_variant` (
  `products_id` BIGINT UNSIGNED NOT NULL,
  `variant_id` INT NOT NULL,
  INDEX `fk_product_variant_products1_idx` (`products_id` ASC) VISIBLE,
  INDEX `fk_product_variant_variant1_idx` (`variant_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_variant_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `martsnp_project`.`products` (`id`),
  CONSTRAINT `product_variant_variant_id`
    FOREIGN KEY (`variant_id`)
    REFERENCES `martsnp_project`.`variant` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `martsnp_project`.`sellers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `martsnp_project`.`sellers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subscription` DATETIME NOT NULL,
  `end_limit` INT NOT NULL DEFAULT '7',
  `users_id` BIGINT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sellers_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_sellers_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `martsnp_project`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
